# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='their_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='their_points',
        ),
    ]
