# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20191122_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='question',
            name='active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='draft',
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.FileField(default=True, upload_to='answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, upload_to='questions'),
        ),
    ]
